
		
HealBot_Plugin_ThreatDefaults = {
  Profile="Global",
}

HealBot_Plugin_Threat_ConfigDefaults = {
    OnlyShowOnDemand = {["Global"] = false},
	frameLocked = {["Global"] = false},
	frameWidth = {["Global"] = 180},
	frameX = {["Global"] = -1},
	frameY = {["Global"] = -1},
	frameR = {["Global"] = 1},
	frameG = {["Global"] = 1},
	frameB = {["Global"] = 1},
	frameA = {["Global"] = 0.05},
	borderR = {["Global"] = 1},
	borderG = {["Global"] = 1},
	borderB = {["Global"] = 1},
	borderA = {["Global"] = 0.25},
	headerR = {["Global"] = 0.1},
	headerG = {["Global"] = 0.1},
	headerB = {["Global"] = 0.1},
	headerA = {["Global"] = 0.9},
	coltype = {["Global"] = 2},
	barR = {["Global"] = 0.4},
	barG = {["Global"] = 0.4},
	barB = {["Global"] = 0.4},
	barA = {["Global"] = 0.7},
	tankcoltype = {["Global"] = 2},
	tankbarR = {["Global"] = 0.9},
	tankbarG = {["Global"] = 0.1},
	tankbarB = {["Global"] = 0.1},
	yourcoltype = {["Global"] = 2},
	yourbarR = {["Global"] = 0.1},
	yourbarG = {["Global"] = 0.1},
	yourbarB = {["Global"] = 0.9},
	titletext = {["Global"] = HEALBOT_PLUGIN_THREAT},
	titlebackR = {["Global"] = 1},
	titlebackG = {["Global"] = 1},
	titlebackB = {["Global"] = 1},
	titlebackA = {["Global"] = 0.4},
	titletextR = {["Global"] = 0.58},
	titletextG = {["Global"] = 0.58},
	titletextB = {["Global"] = 0.58},
	titletextA = {["Global"] = 0.9},
	maxBars = {["Global"] = 5},
	texture = {["Global"] = HealBot_Default_Textures[8].name},
	height = {["Global"] = 20},
	rowspace = {["Global"] = 0},
	txtcoltype = {["Global"] = 1},
	bartxtR = {["Global"] = 0.8},
	bartxtG = {["Global"] = 0.8},
	bartxtB = {["Global"] = 0.8},
	bartxtA = {["Global"] = 0.9},
	tanktxtcoltype = {["Global"] = 1},
	tankbartxtR = {["Global"] = 0.8},
	tankbartxtG = {["Global"] = 0.8},
	tankbartxtB = {["Global"] = 0.8},
	yourtxtcoltype = {["Global"] = 1},
	yourbartxtR = {["Global"] = 0.8},
	yourbartxtG = {["Global"] = 0.8},
	yourbartxtB = {["Global"] = 0.8},
	hdrtxtR = {["Global"] = 1},
	hdrtxtG = {["Global"] = 0.1},
	hdrtxtB = {["Global"] = 0.1},
	hdrtxtA = {["Global"] = 1},
	font = {["Global"] = HealBot_Default_Font},
	fontsize = {["Global"] = 11},
	txtoutline = {["Global"] = 1},
	txtoutline = {["Global"] = 1},
	fluidbars = {["Global"] = true},
	fluidfreq = {["Global"] = 10},
	minthreatpct = {["Global"] = 10},
	playertxtchars = {["Global"] = 0},
	mobtxtchars = {["Global"] = 0},
}

HealBot_Plugin_Threat = {};
HealBot_Plugin_Threat_Config = {};