local _, L = ...

L.Locals ["enGB"] = {
	["LanguageUsed"]		= "English (Great Britain)",
	["TranslatedBy"]		= " by Kauf (Horde) on Server Pagle",

-- Text
	["txtLoaded"] 			= "LFG113 Loaded, use /lfg to display. Version ",
	["txtUpdate"]			= "New Update Available",
	["txtUpdateMessage"]	= "The version of LFG113 is out of date. Please update",
	["txtInvalidAny"]		= "Invalid instance selected. You can not use 'Select Any'",
	["txtInvalidInst"]		= "Invalid instance selected.",
	["txtMissingRole"]		= "Missing role.",
	["DPS"]					= "DPS",
	["Tank"]				= "Tank",
	["Heal"]				= "Heal",
	["NeedAll"]				= "need all",
	["txtRoleType"]			= { "for the dungeon", "for the raid", "to do some questing in", "to PVP in", "" },
	["txtNotes"]			= "Update Notes:",
	["txtRoles"]			= "Roles",
	["txtInstances"]		= "Instances",
	["txtCustomText"]		= "Custom Text",
	["txtLevel"]			= "Level",
	["txtReport"]			= "Report",
	["txtReportedBy"]		= "Issue reported by",
	["txtOn"]				= "on",
	["txtBy"]				= "by",
	["txtCounts"]			= "Report(s)",
	["txtSaveQuestion"]		= "What would you like to save this as?",
	["txtReportQuestion"]	= "Who do you want to report?",
	["txtAnd"]				= "and",
	["txtOr"]				= "or",
	["txtFor"]				= "for",
	["txtGuildRun"]			= "Guild Run",
	["txtAddToBlackList"]	= "Add to Black List",
	["txtNeed"]				= "Need",
	["txtGTG"]				= "then GTG",
	["txtDefaultWhispers"]	= {
		["Accept"]			= "You can come along with us if you want to.",
		["Decline"]			= "I'm sorry but Im not taking you on this adventure to {i}.",
		["Join"]			= "Level {l} {c} {r}",
		["Invite"]			= "I sent an invite to you so you can join us to {t} {i}",
		["Missing"]			= "Please whisper me your level AND role eg. '60 tank/dps' or more specific 'level 60 warrior dps/tank'",
		["Guild"]			= "I sent a Guild invite to you to so you can join us {t} {i}",
		["whisperPartyLeader"]= "{p} is looking for the same instance we are."
	},
	["txtDefaultSearch"]	= {
		["LFG"]				= "{l} {c} {r} LFG {i} {s}",
		["LFM"]				= "LF{n}M {r} for {i} {s} {g}",
	},
	["txtClasses"]		= {
		["Druid"]		= "Druid",
		["Hunter"]		= "Hunter",
		["Mage"]		= "Mage",
		["Rogue"]		= "Rogue",
		["Paladin"]		= "Paladin",
		["Priest"]		= "Priest",
		["Shaman"]		= "Shaman",
		["Warlock"]		= "Warlock",
		["Warrior"]		= "Warrior",
	},

	-- Labels
	["lblChannelLoading"]	= "Enable Channel Loading/Unloading",
	["lblWhatYouNeed"]		= "What do you need in your group:",
	["lblWhatToJoinAs"]		= "What do you want to join a group as:",
	["lblWhatYouView"]		= "Viewing both LFG/LFM:",
	["lblActivity"]			= "Activity",
	["lblKeybind"]			= "Keybind",
	["lblAccurate"]			= "Accurate scan (may slow down system)",
	["lblNotifications"]	= "Notifications/Alerts",
	["lblBroadcast"]		= "Channels to broadcast on",
	["lblTTB"]				= "Time To Broadcast",
	["lblTimeToLive"]		= "Message Life",
	["lblAutoWhisper"]		= "Auto Whisper",
	["lblMessDecline"]		= "Message when you DECLINE someone",
	["lblMessAccept"]		= "Message when you ACCEPT someone",
	["lblMessJoin"]			= "Message when you want to JOIN a group",
	["lblMessInvite"]		= "Message when you INVITE to your group",
	["lblMessGuildInvite"]	= "Message when you INVITE Guild to your group",
	["lblMessMissing"]		= "Message when whispered with missing info",
	["lblDesignType"]		= "Design Type (Requires reload)",
	["lblSettings"]			= "Settings",
	["lblFreeMovingEye"]	= "Search Eye on Minimap",
	["lblUseDMnotVC"]		= "Deadmines Search Initials",
	["lblAdditionalChannel"]= "Additional channel to monitor",
	["lblSavedSearches"]	= "Saved Searches",
	["lblPlayer"]			= "Player",
	["lblIssue"]			= "Issue",
	["lblLanguage"]			= "Language",
	["lblSyncBlackList"]	= "Black list syncronization",
	["lblGroup"]			= "Group",
	["lblPremades"]			= "Premades",
	["lblChangeLanguage"]	= "Interface Language (Requires /reload)",
	["lblCommLanguage"]		= "Communication Language",
	["lblOutput"]			= "Output",
	["lblLFG"]				= "Join Group Broadcast string format",
	["lblLFM"]				= "Create Group Broadcast string format",

	-- Pull Downs
	["lblSelectAny"]		= "Select Any",
	["lblSelectNone"]		= "Select None",
	["cmbActivityPull"]		= { "Dungeons", "Raids", "PVP", "Custom" },
	["cmbLanguage"]			= {
		["frFR"]			= { 1,  false, "Français (France)" },
		["deDE"]			= { 2,  true,  "Deutsche (Deutschland)" },
		["enGB"]			= { 3,  true,  "English (Great Britain)" },
		["enUS"]			= { 4,  true,  "English (America)" },
		["itIT"]			= { 5,  false, "Italiano (Italia)" },
		["koKR"]			= { 6,  false, "한국어 (대한민국)" },
		["zhCN"]			= { 7,  false, "中文 (中国) (简化的)" },
		["zhTW"]			= { 8,  false, "中文 (台灣)" },
		["ruRU"]			= { 9,  true, "русский (Россия)" },
		["esES"]			= { 10, true,  "Español (España)" },
		["esMX"]			= { 11, true,  "Español (Mexico)" },
		["ptBR"]			= { 12, false, "Português (Brasil)" },
	},

	-- Settings TABS
	["tabGeneral"]			= { "General", 57 },
	["tabCommunication"]	= { "Communication", 96 },
	["tabWhisper"]			= { "Whispers", 64 },
	["tabDisplay"]			= { "Display", 70 },
	["tabPremade"]			= { "Premades", 35 },
	["tabBlackList"]		= { "Black list", 65 },
	["tabRatings"]			= { "Rating", 60 },

	-- Popup notification
	["lblLFGNitofication"]	= "LFG113 Popup Notification",
	["lblRequestJoin"]		= "Person requesting to join",

	-- Checkbox
	["chkChannelLoading"]	= "Enable modifications of channels",
	["chkGuildOnly"]		= "Guild only",
	["chkShowAll"]			= "Show all",
	["chkForce"]			= "Force bind to key I",
	["chkEnableScan"]		= "Enabled (Requires reload)",
	["chkEnableSound"]		= "Enable sound",
	["chkPopUpAlert"]		= "Popup alert",
	["chkFullAudio"]		= "Full group audio",
	["chkPingAlert"]		= "Ping alert",
	["chkTrade"]			= "Trade",
	["chkGeneral"]			= "General",
	["chkWorld"]			= "World",
	["chkLFG"]				= "LookingForGroup",
	["chkWhispers"]			= "Accept whispers",
	["chkOriginalDisplay"]	= "Original display",
	["chkFreeMovingEye"]	= "Lock the search eye on the Minimap",
	["chkAlwaysShowEye"]	= "Always show the eye on the Minimap",
	["chkUseDMnotVC"]		= "Use DM for Deadmines, not VC",
	["chkSyncBlackList"]	= "Syncronize List",
	["chkPersonalBL"]		= "Personal Entry",
	["chkCompact"]			= "Compact LFM/LFG",
	["chkDisableAutoNotification"] = "Disable auto broadcast (use Minimap)",

	-- Buttons
	["btnCreateGroup"]		= "Create Group",
	["btnNEWCG"]			= "           Create\n           Group",
	["btnJoinGroup"]		= "Join Group",
	["btnNEWJG"]			= "        Join\n           Group",
	["btnPremades"]			= "Premades",
	["btnNewPremades"]		= "                  Premades",
	["btnActiveSearchs"]	= "Saved Searches",
	["btnNEWAS"]			= "           Saved\n                Searches",
	["btnBlackList"]		= "Players",
	["btnNEWBL"]			= "             Players",
	["btnSettings"]			= "Settings",
	["btnNEWSettings"]		= "              Settings",
	["btnSearch"]			= "Search",
	["btnCancelSearch"]		= "Stop",
	["btnDefault"]			= "Default",
	["btnAdd"]				= "Add",
	["btnRemove"]			= "Remove",
	["btnAccept"]			= "Accept",
	["btnDecline"]			= "Decline",
	["btnInvite"]			= "Invite",
	["btnJoin"]				= "Join",
	["btnNotify"]			= "Notify",
	["btnAddSearch"]		= "Save",
	["btnCancel"]			= "Cancel",
	["btnReport"]			= "Report",
	["btnViewNotes"]		= "Update notes",
	["btnLoad"]				= "Load",
	["btnUnload"]			= "Unload",
	["btnClear"]			= "Reset",
	["btnAcknowledge"]		= "Acknowledge",
	["btnBoth"]				= "Both",
	["btnReload"]			= "Reload",

	-- Popups
	["pupChannelLoading"]	= "Enable the ability to load and unload channels",
	["pupGuildOnly"]		= "Show only Guild activities",
	["pupShowall"]			= "Show all dungeons",
	["pupForce"]			= "Force the system to use the I keybind to open and close the LFG113",
	["pupAccurate"]			= "Enable accurate scanning, may slow down game on slow machines",
	["pupBroadcast"]		= "Sets the re-broadcast time in seconds (Requires reload)",
	["pupTimeToLive"]		= "The number of seconds we wait for a person in chat to repeat a message before we consider their last one dead and remove it from the display.",
	["pupEnableSound"]		= "Sound is enabled for the addon",
	["pupPopuAlert"]		= "Allow a popup when someone requests invite",
	["pupFullGroup"]		= "Notification via sound when your group is full.",
	["pupPingAlert"]		= "Allow audio ping when someone requests invite",
	["pupTrade"]			= "Enable broadcasting to Trade Channel",
	["pupWorld"]			= "Enable broadcasting to World Channel",
	["pupGeneral"]			= "Enable broadcasting to General Channel",
	["pupLFG"]				= "Enable broadcasting to LookingForGroup Channel",
	["pupDisplayType"]		= "Display buttons and future display updates for addon in classic display. Requires reload",
	["pupAcceptWhispers"]	= "Auto invite whispers that say their roll/level and if you need that class.",
	["pupFreeMovingEye"]	= "Lock/Unlock the search eye from the minimap",
	["pupResetEye"]			= "Reset the position of the EYE to the Minimap if you cant find it",
	["pupAlwaysShowEye"]	= "Always show the Eye on the minimap or only when you are actively searching",
	["pupUseDMnotVC"]		= "When enabled use DM for Deadmines, not VC",
	["pupSyncBlackList"]	= "Enable syncronization of the Black List with others on the network",
	["pupPersonalBL"]		= "Do not sync this entry, its personal",
	["pupCompact"]			= "Use this to compact the LFG/LFM display to smaller lines compromising information",
	["pupDisableAutoNotification"] = "Disables automatic notification to broadcast while searching, instead you have to SHIFT-LEFT CLICK the minimap icon to broadcast when you are ready",
	["pupActiveSearch"]		= {
		{ "Classic Looking For Group", 1, 1, 1 },
		{ "You have an active search going!", 1, 1, 0 }, { "\n" },
		{ "Left click          - Open/close", 0, 1, 1},
		{ "Right click        - Move icon", 0, 1, 1 },
		{ "Shift-Left click - Broadcast Search", 0, 1, 1},
	},

	["pupHowtoUse"]			= {
		{ "HOW TO USE:", 1, 1, 1 }, { "\n" },
		{ "Type in any text. You can use special format strings listed below:", 0, 1, 1},
		{ "   - {p} The player whom you are responding to", 1, 1, 0 },
		{ "   - {i} Instance", 1, 1, 0 },
		{ "   - {s} Custom string", 1, 1, 0 },
		{ "   - {t} Special string containing 'Type' of instance.", 1, 1, 0 },
		{ "   - {l} Your level", 1, 1, 0 },
		{ "   - {c} Your class", 1, 1, 0 },
		{ "   - {r} Your role", 1, 1, 0 },
		{ "   - {n} Number of available spaces left", 1, 1, 0 },
		{"    - {g} Appends then GTG at end when one available space is left", 1, 1, 0},
		{ "\n" },
		{ "{t} will return ONE of the strings depending on the instance type selected via the pulldown:", 0, 1, 1 },
		{ "   - Dungeons selected: 'for the dungeon'", 1, 1, 0 },
		{ "   - Raids Selected: 'for the raid'", 1, 1, 0 },
		{ "   - Questing Selected: 'to do some questing in'", 1, 1, 0 },
		{ "   - PVP Selected: 'to PVP in'", 1, 1, 0 }, { "\n" },
		{ " Example: if you are a Warrior level 19 who has both DPS and TANK selected -", 0, 1, 1 },
		{ "   Level {l} {c} {r}", 1, 1, 0},
		{ "     will output 'Level 19 Warrior Tank/DPS'", 1, 1, 0}
	},

	-- Dungeons
	-- 	= {#people, Name On Pulldown, lowest entry level, highest entry level, text to display in chat,  {#tank,#heals,#dps}, { ["keyword"]=1, ... }, "use PulldownSecondChance #8" }
	["PulldownInstance"]		= {
		["any"]			= {1, "Select One", 1, 60, "Any", {1,1,3}, { } },
		["rfc"]			= {5, "Ragefire Chasm", 13, 18, "RFC", {1,1,3}, { [" rfc "]=1, [" ragefire "]=1, [" ragefire chasm "]=1 }, },
		["wc"]			= {5, "Wailing Caverns", 17, 24, "WC", {1,1,3}, { [" wc "]=1, [" wailing caverns "]=1 },  },
		["vc"]			= {5, "The Deadmines", 17, 26, "VC", {1,1,3}, { [" vc "]=1, [" deadmines "]=1, [" van cleef "]=1 }, },
		["sfk"]			= {5, "Shadowfang Keep", 22, 30, "SFK", {1,1,3}, { [" sfk "]=1, [" shadowfang keep "]=1 }, },
		["bfd"]			= {5, "Blackfathom Deeps", 24, 32, "BFD", {1,1,3}, { [" bfd "]=1, [" blackfathom deeps "]=1 }, },
		["stocks"]		= {5, "The Stockade", 24, 32, "Stocks", {1,1,3}, { [" stocks "]=1, [" stockade "]=1 }, },
		["gnomer"]		= {5, "Gnomeregan", 29, 38, "Gnomer", {1,1,3}, { [" gnomer "]=1, [" gnomeregan "]=1 }, },
		["rfk"]	 		= {5, "Razorfen Kraul", 29, 38, "RFK", {1,1,3}, { [" rfk "]=1, [" razorfen kraul "]=1 }, },
		["internalsm"]	= {5, "The Scarlet Monastery", 26, 45, "SM", {1,1,3}, {}, "1:sm gy!1:sm lib!1:sm arm!1:sm cath!1:internalsm" },
		["sm gy"]		= {5, "The Scarlet Monastery Graveyard", 26, 36, "SM GY", {1,1,3}, { [" sm g"]=1, [" graveyard "]=1, [" gy "]=1 }, "1:sm gy!1:internalsm" },
		["sm lib"]		= {5, "The Scarlet Monastery Library", 29, 39, "SM Lib", {1,1,3}, { [" sm l"]=1, [" library "]=1, [" lib "]=1 }, "1:sm lib!1:internalsm" },
		["sm arm"]		= {5, "The Scarlet Monastery Armory", 32, 42, "SM Arm", {1,1,3}, { [" sm a"]=1, [" armory "]=1, [" arm "]=1 }, "1:sm arm!1:internalsm" },
		["sm cath"]		= {5, "The Scarlet Monastery Cathedral", 34, 45, "SM Cath", {1,1,3}, { [" sm c"]=1, [" cathedral "]=1, [" cath "]=1 }, "1:sm cath!1:internalsm" },
		["rfd"]			= {5, "Razorfen Downs", 37, 46, "RFD", {1,1,3}, { [" rfd "]=1, [" razorfen downs "]=1 }, },
		["internalulda"]= {5, "Uldaman", 41, 51, "Ulda", {1,1,3}, {}, "1:ulda front!1:ulda back!1:internalulda" },
		["ulda front"]	= {5, "Uldaman Front", 41, 51, "Ulda Front", {1,1,3}, { [" ulda front "]=1, [" front ulda "]=1, [" uldaman front "]=1, [" front uldaman "]=1 }, "1:ulda front!1:internalulda" },
		["ulda back"]	= {5, "Uldaman Back", 41, 51, "Ulda Back", {1,1,3}, { [" ulda back "]=1, [" back ulda "]=1, [" uldaman back "]=1, [" back uldaman "]=1 }, "1:ulda back!1:internalulda" },
		["zf"]			= {5, "Zul'Farrak", 42, 46, "ZF", {1,1,3}, { [" zf "]=1, [" zulfarrak "]=1, [" zul'farrak "]=1 }, },
		["internalmara"]= {5, "Maraudon", 46, 55, "Mara", {1,1,3}, {}, "1:mara purple!1:mara orange!1:mara princess!1:internalmara" },
		["mara purple"]	= {5, "Maraudon Purple", 46, 55, "Mara Purple", {1,1,3}, { [" mara purple "]=1, [" purple mara "]=1, [" maraudon purple "]=1, [" purple maraudon "]=1 }, "1:mara purple!1:internalmara" },
		["mara orange"]	= {5, "Maraudon Orange", 46, 55, "Mara Orange", {1,1,3}, { [" mara orange "]=1, [" orange mara "]=1, [" maraudon orange "]=1, [" orange maraudon "]=1 }, "1:mara orange!1:internalmara" },
		["mara princess"]={5, "Maraudon Princess", 46, 55, "Mara Princess", {1,1,3}, { [" mara princess "]=1, [" princess mara "]=1, [" maraudon princess "]=1, [" princess maraudon "]=1 }, "1:mara princess!1:internalmara" },
		["st"]			= {5, "Temple of Atal'Hakkar", 50, 56, "ST", {1,1,3}, { [" st "]=1, [" atal'hakkar "]=1, [" atalhakkar "]=1 }, },
		["internalbrd"]	= {5, "Blackrock Depths", 52, 60, "BRD", {1,1,3}, {}, "1:brd arena!1:brd anger!1:brd golem!1:internalbrd" },
		["brd arena"]	= {5, "Blackrock Depths Arena", 52, 60, "BRD Arena", {1,1,3}, { [" arena "]=1, [" brd arena "]=1, [" blackrock depths arena "]=1 }, "1:brd arena!1:internalbrd" },
		["brd anger"]	= {5, "Blackrock Depths Anger", 52, 60, "BRD Anger", {1,1,3}, { [" anger "]=1, [" brd anger "]=1, [" brd angerforge "]=1, [" blackrock depths anger "]=1 }, "1:brd anger!1:internalbrd" },
		["brd golem"]	= {5, "Blackrock Depths Golem", 52, 60, "BRD Golem", {1,1,3}, { [" golem "]=1, [" brd golem "]=1, [" blackrock depths golem "]=1 }, "1:brd golem!1:internalbrd" },
		["lbrs"]		= {5, "Lower Blackrock Spire", 55, 60, "LBRS", {1,1,3}, { [" lbrs "]=1, [" lower blackrock "]=1 }, },
		["internaldm"]	= {5, "Dire Maul", 55, 60, "DM", {1,1,3}, {}, "1:dm west!1:dm north!1:dm east!1:dm tribute!1:internaldm" },
		["dm west"]		= {5, "Dire Maul West", 55, 60, "DM West", {1,1,3}, { [" dm w "]=1, [" dm west "]=1, [" west dm "]=1, [" dire maul west "]=1, [" west dire maul "]=1 }, "1:dm west!1:internaldm" },
		["dm north"]	= {5, "Dire Maul North", 55, 60, "DM North", {1,1,3}, { [" dm n "]=1, [" dm north "]=1, [" north dm "]=1, [" dire maul north "]=1, [" north dire maul "]=1 }, "1:dm north!1:internaldm" },
		["dm east"]		= {5, "Dire Maul East", 55, 60, "DM East", {1,1,3}, { [" dm e "]=1, [" dm east "]=1, [" east dm "]=1, [" dire maul east "]=1, [" east dire maul "]=1 }, "1:dm east!1:internaldm" },
		["dm tribute"]	= {5, "Dire Maul Tribute", 55, 60, "DM Tribute", {1,1,3}, { [" tribute "]=1, [" dm tribute "]=1, [" tribute dm "]=1, [" dire maul tribute "]=1, [" tribute dire maul "]=1, [" tribute run "]=1 }, "1:dm tribute!1:internaldm" },
		["internalstrat"]= {5, "Stratholme", 58, 60, "Strat", {1,1,3}, {}, "1:strat live!1:strat dead!1:internalstrat" },
		["strat live"]	= {5, "Stratholme Live", 58, 60, "Strat Live", {1,1,3}, { [" strat live "]=1, [" strat scarlet "]=1, [" live strat "]=1, [" scarlet strat "]=1, [" stratholme live "]=1, [" live stratholme "]=1 }, "1:strat live!1:internalstrat" },
		["strat dead"]	= {5, "Stratholme Dead", 58, 60, "Strat Dead", {1,1,3}, { [" strat dead "]=1, [" strat undead "]=1, [" strat scourge "]=1, [" dead strat "]=1, [" undead strat "]=1, [" scourge strat "]=1, [" ud strat "]=1, [" ud strath "]=1, [" strat ud "]=1, [" stratholme dead "]=1, [" stratholme undead "]=1, [" dead stratholme "]=1, [" undead stratholme "]=1 }, "1:strat dead!1:internalstrat" },
		["scholo"]		= {5, "Scholomance", 58, 60, "Scholo", {1,1,3}, { [" scholo "]=1, [" scholomance "]=1 }, }
	},

	["PulldownSecondChance"] = {
		["sm"]			= {5, "The Scarlet Monastery", 26, 45, "", {1,1,3}, { [" sm "]=1, [" scarlet monastery "]=1, [" sm full "]=1, [" scarlet monastery full "]=1 }, "1:internalsm!1:sm gy!1:sm lib!1:sm arm!1:sm cath" },
		["ulda"]		= {5, "Uldaman", 41, 51, "", {1,1,3}, { [" uld "]=1, [" ulda "]=1, [" uldaman "]=1, [" ulda full "]=1, [" uld full "]=1, [" uldaman full "]=1 }, "1:internalulda!1:ulda front!1:ulda back" },
		["mara"]		= {5, "Maraudon", 46, 55, "", {1,1,3}, { [" mara "]=1, [" maraudon "]=1, [" mara full "]=1, [" maraudon full "]=1 }, "1:internalmara!1:mara purple!1:mara orange!1:mara princess" },
		["brd"]			= {5, "Blackrock Depths", 52, 60, "", {1,1,3}, { [" brd "]=1, [" blackrock depths "]=1, [" brd full "]=1, ["blackrock depths full "]=1 }, "1:internalbrd!1:brd arena!1:brd anger!1:brd golem" },
		["dm"]			= {5, "Dire Maul", 55, 60, "", {1,1,3}, { [" dm "]=1, [" dire maul "]=1, [" dm full "]=1, [" dire maul full "]=1 }, "1:internaldm!1:dm west!1:dm north!1:dm east!1:dm tribute" },
		["strat"]		= {5, "Stratholme", 58, 60, "", {1,1,3}, { [" strat "]=1, [" strath "]=1, [" stratholme "]=1, [" strat full "]=1, [" stratholme full "]=1 }, "1:internalstrat!1:strat live!1:strat dead" }
	},

	-- Raids
	["PulldownRaids"] = {
		["any"]			= {1, "Select One", 1, 60, "Any", {1,1,3}, { } },
		["ubrs"]		= {10, "Upper Blackrock Spire", 55, 60, "UBRS", {1,1,3}, { [" ubrs "]=1, [" upper blackrock "]=1 }, },
		["ony"]			= {40, "Onyxia's Lair", 60, 61, "Ony", {2,8,30}, { [" ony "]=1, [" onyxia "]=1, ["onyxia lair "]=1 }, },
		["zg"]			= {20, "Zul'Gurub", 60, 61, "ZG", {2,4,14}, { [" zg "]=1, [" zul'gurub "]=1, [" zulgurub "]=1, [" zul gurub "]=1 }, },
		["mc"]			= {40, "Molten Core", 60, 61, "MC", {2,8,30}, { [" mc "]=1, [" molten core "]=1 }, },
		["bwl"]			= {40, "Blackwing Lair", 60, 62, "BWL", {2,8,30}, { [" bwl "]=1, [" blackwing lair "]=1 }, },
		["aq20"]		= {20, "Ruins of Ahn'Qiraj", 60, 62, "AQ20", {2,4,14}, { [" aq20 "]=1, [" ruins of ahn"]=1 }, },
		["aq40"]		= {40, "Temple of Ahn'Qiraj", 60, 63, "AQ40", {2,8,30}, { [" aq40 "]=1, [" temple of ahn"]=1 }, },
		["naxx"]		= {40, "Naxxramas", 60, 64, "Naxx", {2,8,30}, { [" naxx "]=1, [" naxxramas "]=1 }, }
	},

	-- PVP
	["PulldownPVP"] = {
		["any"]			= {1, "Select One", 1, 60, "Any", {1,1,3}, { } },
		["av"]			= {5, "Alterac Valley", 1, 60, "AV", {}, { [" av "]=1, [" alterac "]=1 }, },
		["wg"]			= {5, "Warsong Gulch",1 ,60, "WG", {}, { [" wg "]=1, [" warsong "]=1 }, },
		["ab"]			= {5, "Arathi Basin", 1, 60, "AB", {}, { [" ab "]=1, [" arathi basin "]=1 }, },
		["world"]		= {40, "World PVP", 1, 60, "World PVP", {}, { [" world pvp "]=1 }, }
	},

	["Ignore"]	= {
		["ltb"]					= 1,
		["wtb"]					= 1,
		["nights are"]			= 1,
		["recruiting"]			= 1,
		["recruitment"]			= 1,
		["exceptional players"]	= 1,
		["dedicated to"]		= 1,
		["encha"]				= 1,
		["leather"]				= 1,
		["lw"]					= 1,
		["blacksmith"]			= 1,
		["engineer"]			= 1,
		["tailor"]				= 1,
		["alchem"]				= 1
	},
}