local _, L = ...

L.Locals["deDE"] = {
	["LanguageUsed"]		= "Deutsch",
	["TranslatedBy"]		= " by übersetzt von Yuoko",

-- Text
	["txtLoaded"] 			= "LFG113 geladen, nutze /lfg zum Öffnen. ",
	["txtUpdate"]			= "Neues Update verfügbar.",
	["txtUpdateMessage"]	= "Die Betaversion von LFG113 ist veraltet. Bitte Aktualisieren.",
	["txtInvalidAny"]		= "Ungültige Instanz ausgewählt. Sie können nicht 'etwas auswählen' nehmen.",
	["txtInvalidInst"]		= "Ungültige Instanz ausgewählt.",
	["txtMissingRole"]		= "Keine Rolle ausgewählt.",
	["DPS"]					= "DPS",
	["Tank"]				= "Tank",
	["Heal"]				= "Heal",
	["NeedAll"]				= "brauche alle",
	["txtRoleType"]			= { "für die Dungeons", "für den Raid", "zum Questen", "für PVP", "" },
	["txtNotes"]			= "Update Anmerkungen:",
	["txtRoles"]			= "Rollen",
	["txtInstances"]		= "Instanzen",
	["txtCustomText"]		= "Eigener Text",
	["txtLevel"]			= "Level",
	["txtReport"]			= "Meldung",
	["txtReportedBy"]		= "Fehler gemeldet von",
	["txtOn"]				= "an",
	["txtBy"]				= "von",
	["txtCounts"]			= "Meldung(en)",
	["txtSaveQuestion"]		= "Als was möchten Sie das speichern??",
	["txtReportQuestion"]	= "Wen möchten Sie melden?",
	["txtAnd"]				= "und",
	["txtOr"]				= "oder",
	["txtFor"]				= "für",
	["txtGuildRun"]			= "Gilden Run",
	["txtAddToBlackList"]	= "Zur Blacklist hinzufügen",
	["txtNeed"]				= "Brauchen",
	["txtGTG"]				= "dann GTG",
	["txtDefaultWhispers"]	= {
		["Accept"]			= "Du kannst mit kommen, wenn du willst.",
		["Decline"]			= "Entschuldige, aber ich nehme dich nicht mit nach {i}.",
		["Join"]			= "die Stufe {l} {c} {r}",
		["Invite"]			= "Ich sende dir eine Einladung und du kannst beitreten für {t} {i}",
		["Missing"]			= "Bitte Flüster mir dein die Stufe und deine Rolle z.B '60 tank/dps' oder genauer 'die Stufe 60 Krieger dps/tank'",
		["Guild"]			= "Ich sende dir eine Gildeneinladung, dann kannst du beitreten für {t} {i}",
		["whisperPartyLeader"]= "{p} sucht nach der gleichen Instanz."
	},
	["txtDefaultSearch"]	= {
		["LFG"]				= "{l} {c} {r} LFG {i} {s}",
		["LFM"]				= "LF{n}M {r} for {i} {s} {g}",
	},
	["txtClasses"]		= {
		["Druid"]		= "Druide",
		["Hunter"]		= "Jäger",
		["Mage"]		= "Magier",
		["Rogue"]		= "Schurke",
		["Paladin"]		= "Paladin",
		["Priest"]		= "Priester",
		["Shaman"]		= "Schamane",
		["Warlock"]		= "Hexenmeister",
		["Warrior"]		= "Krieger",
	},

	-- Labels
	["lblWhatYouNeed"]		= "Was brauchst du in deiner Gruppe:",
	["lblWhatToJoinAs"]		= "Als was möchtst du der Gruppe beitreten?:",
	["lblWhatYouView"]		= "Beide anzeigen LFG/LFM:",
	["lblActivity"]			= "Aktivität",
	["lblKeybind"]			= "Tastenbelegung",
	["lblAccurate"]			= "Präziser Scan (kann System verlangsamen)",
	["lblNotifications"]	= "Benachrichtigungen/Warnungen",
	["lblBroadcast"]		= "Channels in denen gesendet wird",
	["lblTTB"]				= "Sendezeit",
	["lblTimeToLive"]		= "Nachrichtenleben",
	["lblAutoWhisper"]		= "Automatisch flüstern",
	["lblMessDecline"]		= "Nachricht, wenn Sie jemanden ABLEHNEN",
	["lblMessAccept"]		= "Nachricht, wenn Sie jemanden AKZEPTIEREN",
	["lblMessJoin"]			= "Nachricht, wenn Sie einer Gruppe BEITRETEN",
	["lblMessInvite"]		= "Nachricht, wenn Sie zu Ihrer Gruppe EINLADEN",
	["lblMessGuildInvite"]	= "Nachricht, wenn Sie Gildenmitglieder zu Ihrer Gruppe EINLADEN",
	["lblMessMissing"]		= "Nachricht beim Flüstern wegen fehlender Infos",
	["lblDesignType"]		= "Design Typ (Reload erforderlich)",
	["lblSettings"]			= "Einstellungen",
	["lblFreeMovingEye"]	= "Suchauge auf Minimap",
	["lblUseDMnotVC"]		= "Todesminen Suchinitialien",
	["lblAdditionalChannel"] = "Zusätzlicher zu überwachender Kanal",
	["lblSavedSearches"]	= "Gespeicherte Suchen",
	["lblPlayer"]			= "Spieler",
	["lblIssue"]			= "Problem",
	["lblLanguage"]			= "Sprache",
	["lblSyncBlackList"]	= "Black list syncronization",
	["lblGroup"]			= "Group",
	["lblPremades"]			= "Vorgefertigt",
	["lblChangeLanguage"]	= "Schnittstellen Sprache (Erforderlich / neu laden)",
	["lblCommLanguage"]		= "Kommunikation Sprache",
	["lblOutput"]			= "Ausgabe",
	["lblLFG"]				= "Gruppe beitreten Nachricht",
	["lblLFM"]				= "Gruppe erstellen Nachricht",

	-- Pull Downs
	["lblSelectAny"]		= "etwas auswählen",
	["lblSelectNone"]		= "nichts auswählen",
	["cmbActivityPull"]		= { "Dungeons", "Raids", "PVP", "Benutzerdefiniert" },
	["cmbLanguage"]			= {
		["frFR"]			= { 1,  false, "Français (France)" },
		["deDE"]			= { 2,  true,  "Deutsche (Deutschland)" },
		["enGB"]			= { 3,  true,  "English (Great Britain)" },
		["enUS"]			= { 4,  true,  "English (America)" },
		["itIT"]			= { 5,  false, "Italiano (Italia)" },
		["koKR"]			= { 6,  false, "한국어 (대한민국)" },
		["zhCN"]			= { 7,  false, "中文 (中国) (简化的)" },
		["zhTW"]			= { 8,  false, "中文 (台灣)" },
		["ruRU"]			= { 9,  true, "русский (Россия)" },
		["esES"]			= { 10, true,  "Español (España)" },
		["esMX"]			= { 11, true,  "Español (Mexico)" },
		["ptBR"]			= { 12, false, "Português (Brasil)" },
	},

	-- Settings TABS
	["tabGeneral"]			= { "Allgemein", 70 },
	["tabCommunication"]	= { "Kommunikation", 96 },
	["tabWhisper"]			= { "Nachrichten", 77 },
	["tabDisplay"]			= { "Anzeige", 70 },
	["tabPremade"]			= { "Vorgefertigt", 35 },
	["tabBlackList"]		= { "Schwarze Liste", 92 },
	["tabRatings"]			= { "Bewertung", 60 },

	-- Popup notification
	["lblLFGNitofication"]	= "LFG113 Popup Benachrichtigung",
	["lblRequestJoin"]		= "Person stellt Beitrittsanfrage",

	-- Checkbox
	["chkGuildOnly"]		= "nur Gilde",
	["chkShowAll"]			= "Alle anzeigen",
	["chkForce"]			= "erzwinge Tastenbelegung auf I",
	["chkEnableScan"]		= "Aktiviert (Reload erforderlich)",
	["chkEnableSound"]		= "aktiviere Ton",
	["chkPopUpAlert"]		= "Popup Warnung",
	["chkFullAudio"]		= "Ton bei voller Gruppe",
	["chkPingAlert"]		= "Ping-Alarm",
	["chkTrade"]			= "Handel",
	["chkGeneral"]			= "Allgemein",
	["chkWorld"]			= "Welt",
	["chkLFG"]				= "SucheNachGruppe",
	["chkWhispers"]			= "Erlaube Flüsternachrichten",
	["chkOriginalDisplay"]	= "Original Anzeige",
	["chkFreeMovingEye"]	= "Sperre das Auge auf der Minimap",
	["chkAlwaysShowEye"]	= "Zeige das Auge immer auf der Minimap",
	["chkUseDMnotVC"]		= "Verwenden Sie DM für Todesminen, nicht VC",
	["chkSyncBlackList"]	= "Syncronize List",
	["chkPersonalBL"]		= "Personal Entry",
	["chkCompact"]			= "Compact LFM/LFG",
	["chkDisableAutoNotification"] = "Disable auto broadcast (use Minimap)",

	-- Buttons
	["btnCreateGroup"] 		= "Erstelle Gruppe",
	["btnNEWCG"]			= "          Erstelle\n          Gruppe",
	["btnJoinGroup"]		= "Gruppe beitreten",
	["btnNEWJG"]			= "          Gruppe\n             beitreten",
	["btnPremades"]			= "Vorgefertigt",
	["btnNewPremades"]		= "               Vorgefertigt",
	["btnActiveSearchs"]	= "Gespeicherte Suchen",
	["btnNEWAS"]			= "                  Gespeicherte\n        Suchen",
	["btnBlackList"]		= "Spieler",
	["btnNEWBL"]			= "         Spieler",
	["btnSettings"]			= "Einstellungen",
	["btnNEWSettings"]		= "                    Einstellungen",
	["btnSearch"]			= "Suche",
	["btnCancelSearch"]		= "Halt",
	["btnDefault"]			= "Standard",
	["btnAdd"]				= "Hinzufügen",
	["btnRemove"]			= "Entfernen",
	["btnAccept"]			= "Akzeptieren",
	["btnDecline"]			= "Ablehnen",
	["btnInvite"]			= "Einladen",
	["btnJoin"]				= "Beitreten",
	["btnNotify"]			= "Benachrichtigen",
	["btnAddSearch"]		= "Speichern",
	["btnCancel"]			= "Abbrechen",
	["btnReport"]			= "Melden",
	["btnViewNotes"]		= "Notizen aktualisieren",
	["btnLoad"]				= "Laden",
	["btnUnload"]			= "Unload",
	["btnClear"]			= "Zurücksetzen",
	["btnAcknowledge"]		= "Bestätigen",
	["btnBoth"]				= "Beide",
	["btnReload"]			= "Neu Laden",

	-- Popups
	["pupGuildOnly"]		= "Zeige nur Gildenaktivität",
	["pupShowall"]			= "zeige alle Dungeons",
	["pupForce"]			= "Zwinge das System die Taste I zum öffen und schließen von LFG113 zu verwenden",
	["pupAccurate"]			= "Aktivieren Sie genaues Scannen und verlangsamen Sie möglicherweise das Spiel auf langsamen Computern",
	["pupBroadcast"]		= "Legt die Wiederholungszeit in Sekunden fest (Reload erforderlich)",
	["pupTimeToLive"]		= "Die Anzahl der Sekunden, die gewartet wird, dass eine Person im Chat eine Nachricht wiederholt, bevor wir die letzte als tot betrachten und sie von der Anzeige entfernen.",
	["pupEnableSound"]		= "Ton ist aktiviert für das Addon",
	["pupPopuAlert"]		= "Erlaube Popup wenn jemand beitreten möchte",
	["pupFullGroup"]		= "Benachrichtigung mit Ton, wenn die Gruppe voll ist.",
	["pupPingAlert"]		= "Erlaube Ping-Ton, wenn jemand beitreten möchte.",
	["pupTrade"]			= "Aktiviere senden an Handels Channel",
	["pupWorld"]			= "Aktiviere senden an Welt Channel",
	["pupGeneral"]			= "Aktiviere senden an Allgemein Channel",
	["pupLFG"]				= "Aktiviere senden an SucheNachGruppe Channel",
	["pupDisplayType"]		= "Zeige Buttons und zukünftige Updates für das Addon in Classischer Anzeige. Reload erforderlich",
	["pupAcceptWhispers"]	= "Automatisch Flüsternden einladen, wenn sie Ihnen Rolle/Level mitteilen und Sie die Klasse brauchen.",
	["pupFreeMovingEye"]	= "Sperre/Entsperre das Auge auf der Minimap",
	["pupResetEye"]			= "setze das Auge auf der Minimap zurück, wenn Sie es nicht sehen können.",
	["pupAlwaysShowEye"]	= "Immer das Auge auf der Minimap anzeigen oder nur wenn gesucht wird",
	["pupUseDMnotVC"]		= "Wenn aktiviert wird DM Für Todesminen verwendet, nicht VC",
	["pupSyncBlackList"]	= "Enable syncronization of the Black List with others on the network",
	["pupPersonalBL"]		= "Do not sync this entry, its personal",
	["pupCompact"]			= "Use this to compact the LFG/LFM display to smaller lines compromising information",
	["pupDisableAutoNotification"] = "Disables automatic notification to broadcast while searching, instead you have to SHIFT-LEFT CLICK the minimap icon to broadcast when you are ready",
	["pupActiveSearch"]		= {
		{ "Classic Looking For Group", 1, 1, 1 },
		{ "Sie haben eine aktive suche!", 1, 1, 1 }, { "\n" },
		{ "Linksklick - Öffnen/Schließen", 0, 1, 1},
		{ "Rechtsklick     - Icon bewegen", 0, 1, 1 },
		{ "Shift-Linksklick - senden suche", 0, 1, 1},
	},

	["pupHowtoUse"]			= {
		{ "WIE MAN ES BENUTZT:", 1, 1, 1 }, { "\n" },
		{ "Geben Sie einen beliebigen Text ein. Sie können die unten aufgeführten Sonderformatzeichenfolgen verwenden:", 0, 1, 1},
		{ "   - {p} Der Spieler, dem Sie antworten", 1, 1, 0 },
		{ "   - {i} Instanz", 1, 1, 0 },
		{ "   - {s} Benutzerdefinierte Zeichenfolge", 1, 1, 0 },
		{ "   - {t} Sonderzeichenfolge, die den Instanztyp enthält.", 1, 1, 0 },
		{ "   - {l} Ihr Level", 1, 1, 0 },
		{ "   - {c} Ihre Klasse", 1, 1, 0 },
		{ "   - {r} Ihre Rolle", 1, 1, 0 },
		{ "   - {n} Number of available spaces left", 1, 1, 0 },
		{"    - {g} Appends then GTG at end when one available space is left", 1, 1, 0},
		{ "\n" },
		{ "{t} Gibt abhängig vom dem im Pulldown-Menü ausgewählten Instanztyp EINEN der Strings zurück:", 0, 1, 1 },
		{ "   - Dungeons ausgewählt: 'für die dungeon'", 1, 1, 0 },
		{ "   - Raids ausgewählt: 'für den raid'", 1, 1, 0 },
		{ "   - Questen ausgewählt: 'zum Questen'", 1, 1, 0 },
		{ "   - PVP ausgewählt: 'für PVP'", 1, 1, 0 }, { "\n" },
		{ " Beispiel: wenn Sie ein Kriger des levels 19 sind und haben beides ausgewählt, DPS und TANK -", 0, 1, 1 },
		{ "   Level {l} {c} {r}", 1, 1, 0},
		{ "     wird ausgeben 'Level 19 Krieger Tank/DPS'", 1, 1, 0}
	},

	-- Dungeons
	-- 	= {#people, Name On Pulldown, lowest entry level, highest entry level, text to display in chat,  {#tank,#heals,#dps}, { ["keyword"]=1, ... }, "use PulldownSecondChance #8" }
	["PulldownInstance"]		= {
		["any"]			= {1, "Auswählen", 1, 60, "Irgendeine", {1,1,3}, { }},
		["rfc"]			= {5, "Ragefireabgrund", 13, 18, "RFC", {1,1,3}, { [" rfc "]=1, [" ragefire "]=1, [" ragefire chasm "]=1 }, },
		["wc"]			= {5, "Die Höhlen des Wehklagens", 17, 24, "WC", {1,1,3}, { [" wc "]=1, [" wailing caverns "]=1 },  },
		["vc"]			= {5, "Die Todesminen", 17, 26, "VC", {1,1,3}, { [" vc "]=1, [" deadmines "]=1, [" van cleef "]=1 }, },
		["sfk"]			= {5, "Burg Schattenfang", 22, 30, "SFK", {1,1,3}, { [" sfk "]=1, [" shadowfang keep "]=1 }, },
		["bfd"]			= {5, "Die Tiefschwarze Grotte", 24, 32, "BFD", {1,1,3}, { [" bfd "]=1, [" blackfathom deeps "]=1 }, },
		["stocks"]		= {5, "Das Verlies", 24, 32, "Stocks", {1,1,3}, { [" stocks "]=1, [" stockade "]=1 }, },
		["gnomer"]		= {5, "Gnomeregan", 29, 38, "Gnomer", {1,1,3}, { [" gnomer "]=1, [" gnomeregan "]=1 }, },
		["rfk"]	 		= {5, "Kral der Klingenhauer", 29, 38, "RFK", {1,1,3}, { [" rfk "]=1, [" razorfen kraul "]=1 }, },
		["internalsm"]	= {5, "Das scharlachrote Kloster", 26, 45, "SM", {1,1,3}, {}, "1:sm gy!1:sm lib!1:sm arm!1:sm cath!1:internalsm" },
		["sm gy"]		= {5, "Das Scharlachrote Kloster - Friedhof", 26, 36, "SM GY", {1,1,3}, { [" sm g"]=1, [" graveyard "]=1, [" gy "]=1 }, "1:sm gy!1:internalsm" },
		["sm lib"]		= {5, "Das Scharlachrote Kloster - Bucherei", 29, 39, "SM Lib", {1,1,3}, { [" sm l"]=1, [" library "]=1, [" lib "]=1 }, "1:sm lib!1:internalsm" },
		["sm arm"]		= {5, "Das Scharlachrote Kloster - Waffenkammer", 32, 42, "SM Arm", {1,1,3}, { [" sm a"]=1, [" armory "]=1, [" arm "]=1 }, "1:sm arm!1:internalsm" },
		["sm cath"]		= {5, "Das Scharlachrote Kloster - Kathedrale", 34, 45, "SM Cath", {1,1,3}, { [" sm c"]=1, [" cathedral "]=1, [" cath "]=1 }, "1:sm cath!1:internalsm" },
		["rfd"]			= {5, "Die Hügel der Klingenhauer", 37, 46, "RFD", {1,1,3}, { [" rfd "]=1, [" razorfen downs "]=1 }, },
		["internalulda"]= {5, "Uldaman", 41, 51, "Ulda", {1,1,3}, {}, "1:ulda front!1:ulda back!1:internalulda" },
		["ulda front"]	= {5, "Uldaman vorne", 41, 51, "Ulda Front", {1,1,3}, { [" ulda front "]=1, [" front ulda "]=1, [" uldaman front "]=1, [" front uldaman "]=1 }, "1:ulda front!1:internalulda" },
		["ulda back"]	= {5, "Uldaman hinten", 41, 51, "Ulda Back", {1,1,3}, { [" ulda back "]=1, [" back ulda "]=1, [" uldaman back "]=1, [" back uldaman "]=1 }, "1:ulda back!1:internalulda" },
		["zf"]			= {5, "Zul'Farrak", 42, 46, "ZF", {1,1,3}, { [" zf "]=1, [" zulfarrak "]=1, [" zul'farrak "]=1 }, },
		["internalmara"]= {5, "Maraudon", 46, 55, "Mara", {1,1,3}, {}, "1:mara purple!1:mara orange!1:mara princess!1:internalmara" },
		["mara purple"]	= {5, "Maraudon Purple", 46, 55, "Mara Purple", {1,1,3}, { [" mara purple "]=1, [" purple mara "]=1, [" maraudon purple "]=1, [" purple maraudon "]=1 }, "1:mara purple!1:internalmara" },
		["mara orange"]	= {5, "Maraudon Orange", 46, 55, "Mara Orange", {1,1,3}, { [" mara orange "]=1, [" orange mara "]=1, [" maraudon orange "]=1, [" orange maraudon "]=1 }, "1:mara orange!1:internalmara" },
		["mara princess"]={5, "Maraudon Princess", 46, 55, "Mara Princess", {1,1,3}, { [" mara princess "]=1, [" princess mara "]=1, [" maraudon princess "]=1, [" princess maraudon "]=1 }, "1:mara princess!1:internalmara" },
		["st"]			= {5, "Der Tempel von Atal'Hakkar", 50, 56, "ST", {1,1,3}, { [" st "]=1, [" atal'hakkar "]=1, [" atalhakkar "]=1 }, },
		["internalbrd"]	= {5, "Schwarzfelstiefen", 52, 60, "BRD", {1,1,3}, {}, "1:brd arena!1:brd anger!1:brd golem!1:internalbrd" },
		["brd arena"]	= {5, "Schwarzfelstiefen Arena", 52, 60, "BRD Arena", {1,1,3}, { [" arena "]=1, [" brd arena "]=1, [" blackrock depths arena "]=1 }, "1:brd arena!1:internalbrd" },
		["brd anger"]	= {5, "Schwarzfelstiefen Anger", 52, 60, "BRD Anger", {1,1,3}, { [" anger "]=1, [" brd anger "]=1, [" brd angerforge "]=1, [" blackrock depths anger "]=1 }, "1:brd anger!1:internalbrd" },
		["brd golem"]	= {5, "Schwarzfelstiefen Golem", 52, 60, "BRD Golem", {1,1,3}, { [" golem "]=1, [" brd golem "]=1, [" blackrock depths golem "]=1 }, "1:brd golem!1:internalbrd" },
		["lbrs"]		= {5, "Untere Schwarzfelsspitze", 55, 60, "LBRS", {1,1,3}, { [" lbrs "]=1, [" lower blackrock "]=1 }, },
		["internaldm"]	= {5, "Düsterbruch", 55, 60, "DM", {1,1,3}, {}, "1:dm west!1:dm north!1:dm east!1:dm tribute!1:internaldm" },
		["dm west"]		= {5, "Düsterbruch West", 55, 60, "DM West", {1,1,3}, { [" dm w "]=1, [" dm west "]=1, [" west dm "]=1, [" dire maul west "]=1, [" west dire maul "]=1 }, "1:dm west!1:internaldm" },
		["dm north"]	= {5, "Düsterbruch Nord", 55, 60, "DM North", {1,1,3}, { [" dm n "]=1, [" dm north "]=1, [" north dm "]=1, [" dire maul north "]=1, [" north dire maul "]=1 }, "1:dm north!1:internaldm" },
		["dm east"]		= {5, "Düsterbruch Ost", 55, 60, "DM East", {1,1,3}, { [" dm e "]=1, [" dm east "]=1, [" east dm "]=1, [" dire maul east "]=1, [" east dire maul "]=1 }, "1:dm east!1:internaldm" },
		["dm tribute"]	= {5, "Düsterbruch Tribut", 55, 60, "DM Tribute", {1,1,3}, { [" tribute "]=1, [" dm tribute "]=1, [" tribute dm "]=1, [" dire maul tribute "]=1, [" tribute dire maul "]=1, [" tribute run "]=1 }, "1:dm tribute!1:internaldm" },
		["internalstrat"]= {5, "Stratholme", 58, 60, "Strat", {1,1,3}, {}, "1:strat live!1:strat dead!1:internalstrat" },
		["strat live"]	= {5, "Stratholme Live", 58, 60, "Strat Live", {1,1,3}, { [" strat live "]=1, [" strat scarlet "]=1, [" live strat "]=1, [" scarlet strat "]=1, [" stratholme live "]=1, [" live stratholme "]=1 }, "1:strat live!1:internalstrat" },
		["strat dead"]	= {5, "Stratholme Dead", 58, 60, "Strat Dead", {1,1,3}, { [" strat dead "]=1, [" strat undead "]=1, [" strat scourge "]=1, [" dead strat "]=1, [" undead strat "]=1, [" scourge strat "]=1, [" ud strat "]=1, [" ud strath "]=1, [" strat ud "]=1, [" stratholme dead "]=1, [" stratholme undead "]=1, [" dead stratholme "]=1, [" undead stratholme "]=1 }, "1:strat dead!1:internalstrat" },
		["scholo"]		= {5, "Scholomance", 58, 60, "Scholo", {1,1,3}, { [" scholo "]=1, [" scholomance "]=1 }, }
	},

	["PulldownSecondChance"] = {
		["sm"]			= {5, "Das scharlachrote Kloster", 26, 45, "", {1,1,3}, { [" sm "]=1, [" scarlet monastery "]=1, [" sm full "]=1, [" scarlet monastery full "]=1 }, "1:internalsm!1:sm gy!1:sm lib!1:sm arm!1:sm cath" },
		["ulda"]		= {5, "Uldaman", 41, 51, "", {1,1,3}, { [" uld "]=1, [" ulda "]=1, [" uldaman "]=1, [" ulda full "]=1, [" uld full "]=1, [" uldaman full "]=1 }, "1:internalulda!1:ulda front!1:ulda back" },
		["mara"]		= {5, "Maraudon", 46, 55, "", {1,1,3}, { [" mara "]=1, [" maraudon "]=1, [" mara full "]=1, [" maraudon full "]=1 }, "1:internalmara!1:mara purple!1:mara orange!1:mara princess" },
		["brd"]			= {5, "Schwarzfelstiefen", 52, 60, "", {1,1,3}, { [" brd "]=1, [" blackrock depths "]=1, [" brd full "]=1, ["blackrock depths full "]=1 }, "1:internalbrd!1:brd arena!1:brd anger!1:brd golem" },
		["dm"]			= {5, "Düsterbruch", 55, 60, "", {1,1,3}, { [" dm "]=1, [" dire maul "]=1, [" dm full "]=1, [" dire maul full "]=1 }, "1:internaldm!1:dm west!1:dm north!1:dm east!1:dm tribute" },
		["strat"]		= {5, "Stratholme", 58, 60, "", {1,1,3}, { [" strat "]=1, [" strath "]=1, [" stratholme "]=1, [" strat full "]=1, [" stratholme full "]=1 }, "1:internalstrat!1:strat live!1:strat dead" }
	},

	-- Raids
	["PulldownRaids"] = {
		["any"]			= {1, "Auswählen", 1, 60, "Irgendeine", {1,1,1}, { }, },
		["ubrs"]		= {10, "Obere Schwarzfelsspitze", 55, 60, "UBRS", {1,1,3}, { [" ubrs "]=1, [" upper blackrock "]=1 }, },
		["ony"]			= {40, "Onyxias Hort", 60, 61, "Ony", {2,8,30}, { [" ony "]=1, [" onyxia "]=1, ["onyxia lair "]=1 }, },
		["zg"]			= {20, "Zul'Gurub", 60, 61, "ZG", {2,4,14}, { [" zg "]=1, [" zul'gurub "]=1, [" zulgurub "]=1, [" zul gurub "]=1 }, },
		["mc"]			= {40, "Geschmolzener Kern", 60, 61, "MC", {2,8,30}, { [" mc "]=1, [" molten core "]=1 }, },
		["bwl"]			= {40, "Pechschwingenhort", 60, 62, "BWL", {2,8,30}, { [" bwl "]=1, [" blackwing lair "]=1 }, },
		["aq20"]		= {20, "Ruinen von Ahn'Qiraj", 60, 62, "AQ20", {2,4,14}, { [" aq20 "]=1, [" ruins of ahn"]=1 }, },
		["aq40"]		= {40, "Tempel von Ahn'Qiraj", 60, 63, "AQ40", {2,8,30}, { [" aq40 "]=1, [" temple of ahn"]=1 }, },
		["naxx"]		= {40, "Naxxramas", 60, 64, "Naxx", {2,8,30}, { [" naxx "]=1, [" naxxramas "]=1 }, }
	},

	-- PVP
	["PulldownPVP"] = {
		["any"]			= {1, "Auswählen", 1, 60, "Irgendeine", {1,1,1}, { }, },
		["av"]			= {5, "Alteractal", 1, 60, "AV", {}, { [" av "]=1, [" alterac "]=1 }, },
		["wg"]			= {5, "Kriegshymnenschlucht",1 ,60, "WG", {}, { [" wg "]=1, [" warsong "]=1 }, },
		["ab"]			= {5, "Arathibecken", 1, 60, "AB", {}, { [" ab "]=1, [" arathi basin "]=1 } },
		["world"]		= {40, "World PVP", 1, 60, "World PVP", {}, { [" world pvp "]=1 }, }
	},

	["Ignore"]	= {
		["ltb"]					= 1,
		["wtb"]					= 1,
		["nights are"]			= 1,
		["recruiting"]			= 1,
		["recruitment"]			= 1,
		["exceptional players"]	= 1,
		["dedicated to"]		= 1,
		["encha"]				= 1,
		["leather"]				= 1,
		["lw"]					= 1,
		["blacksmith"]			= 1,
		["engineer"]			= 1,
		["tailor"]				= 1,
		["alchem"]				= 1
	}
}