local _, L = ...

L.Locals ["ruRU"] = {
	["LanguageUsed"]		= "Russian (ruRU)",
	["TranslatedBy"]		= " by Swaity",

-- Text
	["txtLoaded"] 			= "LFG113 загружен, используйте /lfg для открытия дисплея.",
	["txtUpdate"]			= "Доступно новое обновление.",
	["txtUpdateMessage"]	= "Версия LFG113 устарела. Пожалуйста обновите.",
	["txtInvalidAny"]		= "Вы выбрали неверный инст. Вы не можете использовать 'Выбрать любой'",
	["txtInvalidInst"]		= "Выбран неверный инст.",
	["txtMissingRole"]		= "Недостающая роль.",
	["DPS"]					= "Дамагер",
	["Tank"]				= "Танк",
	["Heal"]				= "Лекарь",
	["NeedAll"]				= "Нужны все",
	["txtRoleType"]			= { "для данжа", "для рейда", "для квестов", "ПВП", "" },
	["txtNotes"]			= "Обновление заметок:",
	["txtRoles"]			= "Роли",
	["txtInstances"]		= "Инсты",
	["txtCustomText"]		= "Текст",
	["txtLevel"]			= "Уровень",
	["txtReport"]			= "Сообщение",
	["txtReportedBy"]		= "О проблеме сообщили",
	["txtOn"]				= "on",
	["txtBy"]				= "by",
	["txtCounts"]			= "Репорты",
	["txtSaveQuestion"]		= "Что бы вы хотели сохранить это как?",
	["txtReportQuestion"]	= "Кому вы хотите сообщить?",
	["txtAnd"]				= "и",
	["txtOr"]				= "или",
	["txtFor"]				= "для",
	["txtGuildRun"]			= "Гильд Ран",
	["txtAddToBlackList"]	= "Добавить в черный список",
	["txtNeed"]				= "Необходимость",
	["txtGTG"]				= "затем ГТГ",
	["txtDefaultWhispers"]	= {
		["Accept"]			= "Вы можете пойти с нами, если вы хотите.",
		["Decline"]			= "Извини, но я не возьму тебя в это приключение {i}.",
		["Join"]			= "Уровень {l} {c} {r}",
		["Invite"]			= "Я отправил вам приглашение, чтобы вы могли присоединиться к нам в {t} {i}",
		["Missing"]			= "Пожалуйста, напиши мне свой уровень и роль, например. '60 танк / дпс' или более конкретно 'уровень 60 воин дпс / танк'",
		["Guild"]			= "Я отправил вам приглашение в гильдию, чтобы вы могли присоединиться к нам. {t} {i}",
		["whisperPartyLeader"]= "{p} ищет тот же инст, что и мы."
	},
	["txtDefaultSearch"]	= {
		["LFG"]				= "{l} {c} {r} LFG {i} {s}",
		["LFM"]				= "LF{n}M {r} for {i} {s} {g}",
	},
	["txtClasses"]		= {
		["Druid"]		= "друид",
		["Hunter"]		= "охотник",
		["Mage"]		= "маг",
		["Rogue"]		= "Разбойник",
		["Paladin"]		= "паладин",
		["Priest"]		= "священник",
		["Shaman"]		= "шаман",
		["Warlock"]		= "Чернокнижник",
		["Warrior"]		= "воитель",
	},

	-- Labels
	["lblChannelLoading"]	= "Включить загрузку / выгрузку канала",
	["lblWhatYouNeed"]		= "Что вам нужно в вашей группе:",
	["lblWhatToJoinAs"]		= "Как вы хотите присоединиться к группе:",
	["lblWhatYouView"]		= "Просмотр обоих LFG / LFM:",
	["lblActivity"]			= "Активность",
	["lblKeybind"]			= "Забиндить клавишу",
	["lblAccurate"]			= "Точное сканирование (может замедлить работу системы)",
	["lblNotifications"]	= "Уведомления",
	["lblBroadcast"]		= "Каналы для трансляции на",
	["lblTTB"]				= "Время до трансляции",
	["lblTimeToLive"]		= "Живое сообщение",
	["lblAutoWhisper"]		= "Авто висп",
	["lblMessDecline"]		= "Сообщение, когда вы ОТКАЗЫВАЕТЕСЬ",
	["lblMessAccept"]		= "Сообщение, когда вы ПРИНИМАЕТЕ кого-то",
	["lblMessJoin"]			= "Сообщение, когда вы хотите ПРИСОЕДИНИТЬСЯ к группе",
	["lblMessInvite"]		= "Сообщение, когда вы ПРИГЛАШАЕТЕ в свою группу",
	["lblMessGuildInvite"]	= "Сообщение, когда вы ПРИГЛАШАЕТЕ гильдию в свою группу",
	["lblMessMissing"]		= "Сообщение, когда висп был пропущен",
	["lblDesignType"]		= "Тип дизайна (требуется перезагрузка)",
	["lblSettings"]			= "Настройки",
	["lblFreeMovingEye"]	= "Искать иконку на миникарте",
	["lblUseDMnotVC"]		= "Инициалы поиска мин",
	["lblAdditionalChannel"]= "Дополнительный канал для мониторинга",
	["lblSavedSearches"]	= "Сохранить поиски",
	["lblPlayer"]			= "Игрок",
	["lblIssue"]			= "Вопрос",
	["lblLanguage"]			= "Язык",
	["lblSyncBlackList"]	= "Синхронизация черного списка",
	["lblGroup"]			= "Группа",
	["lblPremades"]			= "Премейды",
	["lblChangeLanguage"]	= "Загрузить язык аддона (требуется / перезагрузка)",
	["lblCommLanguage"]		= "Язык общения",
	["lblOutput"]			= "Выход",
	["lblLFG"]				= "Присоединиться к группе Строка формата вещания",
	["lblLFM"]				= "Создать группу Строка формата вещания",

	-- Pull Downs
	["lblSelectAny"]		= "Выберите любой",
	["lblSelectNone"]		= "Выберите нет",
	["cmbActivityPull"]		= { "Данжи", "Рейды", "Пвп", "Настраиваемый" },
	["cmbLanguage"]			= {
		["frFR"]			= { 1,  false, "Français (France)" },
		["deDE"]			= { 2,  true,  "Deutsche (Deutschland)" },
		["enGB"]			= { 3,  true,  "English (Great Britain)" },
		["enUS"]			= { 4,  true,  "English (America)" },
		["itIT"]			= { 5,  false, "Italiano (Italia)" },
		["koKR"]			= { 6,  false, "한국어 (대한민국)" },
		["zhCN"]			= { 7,  false, "中文 (中国) (简化的)" },
		["zhTW"]			= { 8,  false, "中文 (台灣)" },
		["ruRU"]			= { 9,  true, "русский (Россия)" },
		["esES"]			= { 10, true,  "Español (España)" },
		["esMX"]			= { 11, true,  "Español (Mexico)" },
		["ptBR"]			= { 12, false, "Português (Brasil)" },
	},

	-- Settings TABS
	["tabGeneral"]			= { "Главное", 57 },
	["tabCommunication"]	= { "Общение", 66 },
	["tabWhisper"]			= { "Виспы", 49 },
	["tabDisplay"]			= { "Дисплей", 58 },
	["tabPremade"]			= { "Премейды", 35 },
	["tabBlackList"]		= { "Черный список", 94 },
	["tabRatings"]			= { "Мои записи", 73 },

	-- Popup notification
	["lblLFGNitofication"]	= "LFG113 Всплывающее уведомление",
	["lblRequestJoin"]		= "Игрок, желающий присоединиться",

	-- Checkbox
	["chkChannelLoading"]	= "Разрешить модификации каналов",
	["chkGuildOnly"]		= "Гильдия только",
	["chkShowAll"]			= "Показать все",
	["chkForce"]			= "Принудительная привязка к клавише I",
	["chkEnableScan"]		= "Включено (требуется перезагрузка)",
	["chkEnableSound"]		= "Включить звук",
	["chkPopUpAlert"]		= "Всплывающее оповещение",
	["chkFullAudio"]		= "Полный групповой звук",
	["chkPingAlert"]		= "Пинг оповещения",
	["chkTrade"]			= "Торговля",
	["chkGeneral"]			= "Общий",
	["chkWorld"]			= "Мир",
	["chkLFG"]				= "Поиск групп",
	["chkWhispers"]			= "Принять висперов",
	["chkOriginalDisplay"]	= "Оригинальный дисплей",
	["chkFreeMovingEye"]	= "Зафиксировать поисковый глаз на миникарте",
	["chkAlwaysShowEye"]	= "Всегда показывать глаз на миникарте",
	["chkUseDMnotVC"]		= "Используйте DM для Deadmines, а не VC",
	["chkSyncBlackList"]	= "Синхронизированный список",
	["chkPersonalBL"]		= "Личный вход",
	["chkCompact"]			= "Компактный LFM/LFG",
	["chkDisableAutoNotification"] = "Disable auto broadcast (use Minimap)",

	-- Buttons
	["btnCreateGroup"]		= "Создать группу",
	["btnNEWCG"]			= "           Создать\n          группу",
	["btnJoinGroup"]		= "Присоединиться к группе",
	["btnNEWJG"]			= "           Присоединиться\n        группе",
	["btnPremades"]			= "Примейды",
	["btnNewPremades"]		= "              Примейды",
	["btnActiveSearchs"]	= "Сохранить поиски",
	["btnNEWAS"]			= "              Сохранить\n         поиски",
	["btnBlackList"]		= "игроки",
	["btnNEWBL"]			= "         игроки",
	["btnSettings"]			= "Настройки",
	["btnNEWSettings"]		= "              Настройки",
	["btnSearch"]			= "Поиск",
	["btnCancelSearch"]		= "Стоп",
	["btnDefault"]			= "По умолчанию",
	["btnAdd"]				= "Добавить",
	["btnRemove"]			= "Удалить",
	["btnAccept"]			= "Принять",
	["btnDecline"]			= "Отказать",
	["btnInvite"]			= "Пригласить",
	["btnJoin"]				= "Присоединиться",
	["btnNotify"]			= "Уведомить",
	["btnAddSearch"]		= "Сохранить",
	["btnCancel"]			= "Отменить",
	["btnReport"]			= "Репорт",
	["btnViewNotes"]		= "Обновить заметки",
	["btnLoad"]				= "Загрузить",
	["btnUnload"]			= "Выгрузить",
	["btnClear"]			= "Сбросить",
	["btnAcknowledge"]		= "Подтвердить",
	["btnBoth"]				= "Оба",
	["btnReload"]			= "Перезарядка",

	-- Popups
	["pupChannelLoading"]	= "Включить возможность загрузки и выгрузки каналов",
	["pupGuildOnly"]		= "Показывать только действия гильдии",
	["pupShowall"]			= "Показывать все данжи",
	["pupForce"]			= "Заставить систему использовать клавишу I, чтобы открыть и закрыть LFG113",
	["pupAccurate"]			= "Включить точное сканирование, может замедлить игру на медленных машинах",
	["pupBroadcast"]		= "Устанавливает время повторной трансляции в секундах (Требуется перезагрузка)",
	["pupTimeToLive"]		= "Количество секунд, в течение которых человек в чате повторяет сообщение, прежде чем удалять его с экрана. ",
	["pupEnableSound"]		= "Звук включен для аддона",
	["pupPopuAlert"]		= "Разрешить всплывающее окно, когда кто-то просит пригласить",
	["pupFullGroup"]		= "Уведомление через звук, когда ваша группа заполнена.",
	["pupPingAlert"]		= "Разрешить звуковой пинг, когда кто-то просит пригласить",
	["pupTrade"]			= "Включить трансляцию на Торговый канал",
	["pupWorld"]			= "Включить трансляцию на Мировой канал",
	["pupGeneral"]			= "Включить трансляцию на Общий канал",
	["pupLFG"]				= "Включить трансляцию на канал Поиска Групп",
	["pupDisplayType"]		= "Кнопки дисплея и будущие обновления дисплея для аддона на классическом дисплее. Требуется перезагрузка",
	["pupAcceptWhispers"]	= "Автоприглашение шепотом, которые пишут их роль / уровень и если вам нужен этот класс.",
	["pupFreeMovingEye"]	= "Закрепить/Открепить глаз поиска из миникарты",
	["pupResetEye"]			= "Сбросьте положение ГЛАЗА на миникарте, если не можете ее найти",
	["pupAlwaysShowEye"]	= "Всегда показывать глаз на миникарте или только когда вы активно ищете",
	["pupUseDMnotVC"]		= "Когда включено использование DM для Deadmines, а не VC",
	["pupSyncBlackList"]	= "Включить синхронизацию черного списка с другими пользователями в сети",
	["pupPersonalBL"]		= "Не синхронизировать эту запись, это персонально",
	["pupCompact"]			= "Используйте это, чтобы сжать дисплей LFG / LFM в меньшие строки",
	["pupDisableAutoNotification"] = "Disables automatic notification to broadcast while searching, instead you have to SHIFT-LEFT CLICK the minimap icon to broadcast when you are ready",
	["pupActiveSearch"]		= {
		{ "Classic Looking For Group", 1, 1, 1 },
		{ "У вас идет активный поиск!", 1, 1, 1 }, { "\n" },
		{ "Левый клик       - Открыть/Закрыть", 0, 1, 1},
		{ "Правый клик      - Перемещение иконки", 0, 1, 1 },
		{ "сдвиг-Левый клик - трансляции Поиск", 0, 1, 1},
	},

	["pupHowtoUse"]			= {
		{ "Как использовать:", 1, 1, 1 }, { "\n" },
		{ "Введите любой текст. Вы можете использовать строки специального формата, перечисленные ниже:", 0, 1, 1},
		{ "   - {p} Игрок, которому вы отвечаете", 1, 1, 0 },
		{ "   - {i} Инст", 1, 1, 0 },
		{ "   - {s} Пользовательская строка", 1, 1, 0 },
		{ "   - {t} Специальная строка, содержащая «Тип» инста.", 1, 1, 0 },
		{ "   - {l} Ваш уровень", 1, 1, 0 },
		{ "   - {c} Ваш класс", 1, 1, 0 },
		{ "   - {r} Ваша роль", 1, 1, 0 },
		{ "   - {n} Number of available spaces left", 1, 1, 0 },
		{"    - {g} Appends then GTG at end when one available space is left", 1, 1, 0},
		{ "\n" },
		{ "{t} вернет ОДНУ из строк в зависимости от типа инста, выбранного с помощью раскрывающегося списка:", 0, 1, 1 },
		{ "   - Выбранные данжи: 'для данжев'", 1, 1, 0 },
		{ "   - Выбранные рейды: 'для рейдов'", 1, 1, 0 },
		{ "   - Выбранные квесты: 'сделать некоторые квесты в'", 1, 1, 0 },
		{ "   - Выбранные ПВП: 'для ПВП в'", 1, 1, 0 }, { "\n" },
		{ " Пример: если вы Воин 19 уровня кто выбирает и Дамагера и Танка -", 0, 1, 1 },
		{ "   Уровень {l} {c} {r}", 1, 1, 0},
		{ "     will output 'Уровень 19 Воин Танк/Дамагер'", 1, 1, 0}
	},

	-- Данжи
	-- 	= {#people, Name On Pulldown, lowest entry level, highest entry level, text to display in chat,  {#танк,#лекарь,#дамагер}, { ["keyword"]=1, ... }, "use PulldownSecondChance #8" }
	["PulldownInstance"]		= {
		["any"]			= {1, "Выбрать один", 1, 60, "Любой", {1,1,3}, { } },
		["rfc"]			= {5, "Огненная пропасть", 13, 18, "ОП", {1,1,3}, { [" rfc "]=1, [" огненная пропасть "]=1, [" огненная пропасть "]=1 }, },
		["wc"]			= {5, "Пещеры Стенаний", 17, 24, "ПС", {1,1,3}, { [" wc "]=1, [" пещеры стенаний "]=1 },  },
		["vc"]			= {5, "Мертвые копи", 17, 26, "Копи", {1,1,3}, { [" vc "]=1, [" шахты "]=1, [" ван клиф "]=1 }, },
		["sfk"]			= {5, "Крепость Темного Клыка", 22, 30, "ктк", {1,1,3}, { [" sfk "]=1, [" крепость темного клыка "]=1 }, },
		["bfd"]			= {5, "Непроглядная Пучина", 24, 32, "НП", {1,1,3}, { [" нп "]=1, [" непроглядная пучина "]=1 }, },
		["stocks"]		= {5, "Тюрьма", 24, 32, "Тюрьма", {1,1,3}, { [" тюрьма "]=1, [" тюрьма "]=1 }, },
		["gnomer"]		= {5, "Гномреган", 29, 38, "Гномер", {1,1,3}, { [" гномер "]=1, [" гномереган "]=1 }, },
		["rfk"]	 		= {5, "Лабиринты Иглошкурых", 29, 38, "ЛИ", {1,1,3}, { [" лабиринты "]=1, [" лабиринты иглошкурых "]=1 }, },
		["internalsm"]	= {5, "Монастырь Алого ордена", 26, 45, "МАО", {1,1,3}, {}, "1:sm gy!1:sm lib!1:sm arm!1:sm cath!1:internalsm" },
		["sm gy"]		= {5, "Монастырь Алого ордена Кладбище", 26, 36, "МАО кладба", {1,1,3}, { [" мао g"]=1, [" graveyard "]=1, [" gy "]=1 }, "1:sm gy!1:internalsm" },
		["sm lib"]		= {5, "Монастырь Алого ордена Библиотека", 29, 39, "МАО библа", {1,1,3}, { [" мао l"]=1, [" library "]=1, [" lib "]=1 }, "1:sm lib!1:internalsm" },
		["sm arm"]		= {5, "Монастырь Алого ордена Оружейная", 32, 42, "МАО оружейка", {1,1,3}, { [" мао a"]=1, [" armory "]=1, [" arm "]=1 }, "1:sm arm!1:internalsm" },
		["sm cath"]		= {5, "Монастырь Алого ордена Кафедральный Собор", 34, 45, "МАО кафедра", {1,1,3}, { [" мао c"]=1, [" cathedral "]=1, [" cath "]=1 }, "1:sm cath!1:internalsm" },
		["rfd"]			= {5, "Курганы Иглошкурых", 37, 46, "КИ", {1,1,3}, { [" ки "]=1, [" курганы иглошкурых "]=1 }, },
		["internalulda"]= {5, "Ульдаман", 41, 51, "Ульда", {1,1,3}, {}, "1:ulda front!1:ulda back!1:internalulda" },
		["ulda front"]	= {5, "Ульдаман начало", 41, 51, "Ульда начало", {1,1,3}, { [" ulda front "]=1, [" front ulda "]=1, [" uldaman front "]=1, [" front uldaman "]=1 }, "1:ulda front!1:internalulda" },
		["ulda back"]	= {5, "Ульдаман конец", 41, 51, "Ульда конец", {1,1,3}, { [" ulda back "]=1, [" back ulda "]=1, [" uldaman back "]=1, [" back uldaman "]=1 }, "1:ulda back!1:internalulda" },
		["zf"]			= {5, "Зуль'Фарак", 42, 46, "ЗФ", {1,1,3}, { [" zf "]=1, [" zulfarrak "]=1, [" zul'farrak "]=1 }, },
		["internalmara"]= {5, "Мародон", 46, 55, "Мара", {1,1,3}, {}, "1:mara purple!1:mara orange!1:mara princess!1:internalmara" },
		["mara purple"]	= {5, "Мародон Пурпурный", 46, 55, "Мара Purple", {1,1,3}, { [" mara purple "]=1, [" purple mara "]=1, [" maraudon purple "]=1, [" purple maraudon "]=1 }, "1:mara purple!1:internalmara" },
		["mara orange"]	= {5, "Мародон Оранжевый", 46, 55, "Мара Orange", {1,1,3}, { [" mara orange "]=1, [" orange mara "]=1, [" maraudon orange "]=1, [" orange maraudon "]=1 }, "1:mara orange!1:internalmara" },
		["mara princess"]={5, "Мародон Принцесса", 46, 55, "Мара Princess", {1,1,3}, { [" mara princess "]=1, [" princess mara "]=1, [" maraudon princess "]=1, [" princess maraudon "]=1 }, "1:mara princess!1:internalmara" },
		["st"]			= {5, "Храм Атал'Хаккара", 50, 56, "ХАХ", {1,1,3}, { [" st "]=1, [" atal'hakkar "]=1, [" atalhakkar "]=1 }, },
		["internalbrd"]	= {5, "Глубины Черной горы", 52, 60, "БРД", {1,1,3}, {}, "1:ГЧГ арена!1:brd anger!1:brd golem!1:internalbrd" },
		["brd arena"]	= {5, "Глубины Черной горы Арена", 52, 60, "ГЧГ Арена", {1,1,3}, { [" arena "]=1, [" brd arena "]=1, [" blackrock depths arena "]=1 }, "1:brd arena!1:internalbrd" },
		["brd anger"]	= {5, "Глубины Черной горы Гнев", 52, 60, "ГЧГ Anger", {1,1,3}, { [" anger "]=1, [" brd anger "]=1, [" brd angerforge "]=1, [" blackrock depths anger "]=1 }, "1:brd anger!1:internalbrd" },
		["brd golem"]	= {5, "Глубины Черной горы Голем", 52, 60, "ГЧГ Golem", {1,1,3}, { [" golem "]=1, [" brd golem "]=1, [" blackrock depths golem "]=1 }, "1:brd golem!1:internalbrd" },
		["lbrs"]		= {5, "Нижний Ярус Черной Горы", 55, 60, "ЛБРС", {1,1,3}, { [" lbrs "]=1, [" lower blackrock "]=1 }, },
		["internaldm"]	= {5, "Забытый Город", 55, 60, "ЗГ", {1,1,3}, {}, "1:dm west!1:dm north!1:dm east!1:dm tribute!1:internaldm" },
		["dm west"]		= {5, "Забытый Город Запад", 55, 60, "ЗГ West", {1,1,3}, { [" dm w "]=1, [" dm west "]=1, [" west dm "]=1, [" dire maul west "]=1, [" west dire maul "]=1 }, "1:dm west!1:internaldm" },
		["dm north"]	= {5, "Забытый Город Север", 55, 60, "ЗГ North", {1,1,3}, { [" dm n "]=1, [" dm north "]=1, [" north dm "]=1, [" dire maul north "]=1, [" north dire maul "]=1 }, "1:dm north!1:internaldm" },
		["dm east"]		= {5, "Забытый Город Восток", 55, 60, "ЗГ East", {1,1,3}, { [" dm e "]=1, [" dm east "]=1, [" east dm "]=1, [" dire maul east "]=1, [" east dire maul "]=1 }, "1:dm east!1:internaldm" },
		["dm tribute"]	= {5, "Забытый Город Дань", 55, 60, "ЗГ Tribute", {1,1,3}, { [" tribute "]=1, [" dm tribute "]=1, [" tribute dm "]=1, [" dire maul tribute "]=1, [" tribute dire maul "]=1, [" tribute run "]=1 }, "1:dm tribute!1:internaldm" },
		["internalstrat"]= {5, "Стратхольм", 58, 60, "Страт", {1,1,3}, {}, "1:strat live!1:strat dead!1:internalstrat" },
		["strat live"]	= {5, "Стратхольм Живой", 58, 60, "Страт Живой", {1,1,3}, { [" strat live "]=1, [" strat scarlet "]=1, [" live strat "]=1, [" scarlet strat "]=1, [" stratholme live "]=1, [" live stratholme "]=1 }, "1:strat live!1:internalstrat" },
		["strat dead"]	= {5, "Стратхольм Мертвый", 58, 60, "Страт Мертвый", {1,1,3}, { [" strat dead "]=1, [" strat undead "]=1, [" strat scourge "]=1, [" dead strat "]=1, [" undead strat "]=1, [" scourge strat "]=1, [" ud strat "]=1, [" ud strath "]=1, [" strat ud "]=1, [" stratholme dead "]=1, [" stratholme undead "]=1, [" dead stratholme "]=1, [" undead stratholme "]=1 }, "1:strat dead!1:internalstrat" },
		["scholo"]		= {5, "Некроситет", 58, 60, "Шоло", {1,1,3}, { [" шоло "]=1, [" некроситет "]=1 }, }
	},

	["PulldownSecondChance"] = {
		["sm"]			= {5, "Монастырь Алого ордена", 26, 45, "", {1,1,3}, { [" мао "]=1, [" scarlet monastery "]=1, [" sm full "]=1, [" scarlet monastery full "]=1 }, "1:internalsm!1:sm gy!1:sm lib!1:sm arm!1:sm cath" },
		["ulda"]		= {5, "Ульдаман", 41, 51, "", {1,1,3}, { [" ульда "]=1, [" ульда "]=1, [" uldaman "]=1, [" ulda full "]=1, [" uld full "]=1, [" uldaman full "]=1 }, "1:internalulda!1:ulda front!1:ulda back" },
		["mara"]		= {5, "Мародон", 46, 55, "", {1,1,3}, { [" мара "]=1, [" мара "]=1, [" mara full "]=1, [" maraudon full "]=1 }, "1:internalmara!1:mara purple!1:mara orange!1:mara princess" },
		["brd"]			= {5, "Глубины Черной горы", 52, 60, "", {1,1,3}, { [" гчг "]=1, [" blackrock depths "]=1, [" brd full "]=1, ["blackrock depths full "]=1 }, "1:internalbrd!1:brd arena!1:brd anger!1:brd golem" },
		["dm"]			= {5, "Забытый Город", 55, 60, "", {1,1,3}, { [" дм "]=1, [" дм "]=1, [" dm full "]=1, [" dire maul full "]=1 }, "1:internaldm!1:dm west!1:dm north!1:dm east!1:dm tribute" },
		["strat"]		= {5, "Стратхольм", 58, 60, "", {1,1,3}, { [" страт "]=1, [" страт "]=1, [" stratholme "]=1, [" strat full "]=1, [" stratholme full "]=1 }, "1:internalstrat!1:strat live!1:strat dead" }
	},

	-- Raids
	["PulldownRaids"] = {
		["any"]			= {1, "Выбрать один", 1, 60, "Любой", {1,1,3}, { } },
		["ubrs"]		= {10, "Верхняя Часть Вершины Черной Горы", 55, 60, "УБРС", {1,1,3}, { [" убрс "]=1, [" upper blackrock "]=1 }, },
		["ony"]			= {40, "Логово Ониксии", 60, 61, "Оня", {2,8,30}, { [" оня "]=1, [" onyxia "]=1, ["onyxia lair "]=1 }, },
		["zg"]			= {20, "Зул'Гуруб", 60, 61, "ЗГ", {2,4,14}, { [" ЗГ "]=1, [" zul'gurub "]=1, [" zulgurub "]=1, [" zul gurub "]=1 }, },
		["mc"]			= {40, "Огненные Недра", 60, 61, "МК", {2,8,30}, { [" мк "]=1, [" molten core "]=1 }, },
		["bwl"]			= {40, "Логово Крыла Тьмы", 60, 62, "БВЛ", {2,8,30}, { [" бвл "]=1, [" blackwing lair "]=1 }, },
		["aq20"]		= {20, "Руины Ан'Киража", 60, 62, "Анкираж руины", {2,4,14}, { [" анкираж руины "]=1, [" руины"]=1 }, },
		["aq40"]		= {40, "Ан'Кираж", 60, 63, "анкираж", {2,8,30}, { [" анкираж "]=1, [" анкираж"]=1 }, },
		["naxx"]		= {40, "Наксрамас", 60, 64, "Накс", {2,8,30}, { [" Накс "]=1, [" naxxramas "]=1 }, }
	},

	-- PVP
	["PulldownPVP"] = {
		["any"]			= {1, "Выбрать один", 1, 60, "Любой", {1,1,3}, { } },
		["av"]			= {5, "Альтеракская долина", 1, 60, "АВ", {}, { [" ав "]=1, [" альтерак "]=1 }, },
		["wg"]			= {5, "Ущелье Песни Войны",1 ,60, "ВСГ", {}, { [" всг "]=1, [" варсонг "]=1 }, },
		["ab"]			= {5, "Низина Арати", 1, 60, "Низина", {}, { [" Низина "]=1, [" арати "]=1 }, },
		["world"]		= {40, "ВПВП", 1, 60, "ВПВ", {}, { [" ворлд пвп "]=1 }, }
	},

	["Ignore"]	= {
		["ltb"]					= 1,
		["wtb"]					= 1,
		["nights are"]			= 1,
		["recruiting"]			= 1,
		["recruitment"]			= 1,
		["exceptional players"]	= 1,
		["dedicated to"]		= 1,
		["encha"]				= 1,
		["leather"]				= 1,
		["lw"]					= 1,
		["blacksmith"]			= 1,
		["engineer"]			= 1,
		["tailor"]				= 1,
		["alchem"]				= 1
	},
}